---
- name: Install MongoDB
  apt:
    name: mongodb
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Configure MongoDB to listen on all IP addresses
  lineinfile:
    dest: /etc/mongodb.conf
    regexp: '^bind_ip'
    line: 'bind_ip = 0.0.0.0'

- name: Start MongoDB service
  service:
    name: mongodb
    state: started
  when: ansible_distribution == 'Ubuntu'

- name: copy user creation script
  template:
    src: mongodb_users.js.j2
    dest: /tmp/mongodb_users

- name: Create MongoDB user with provided username and password
  command: mongo {{ mongodb_database }} /tmp/mongodb_users
  ignore_errors: yes  # Ignore errors if the user already exists
  tags: backend
