---
- name: Installing Mysql  and dependencies
  package:
   name: "{{item}}"
   state: present
   update_cache: yes
  loop:
   - mysql-server
   - mysql-client 
   - python3-mysqldb
   - libmysqlclient-dev
  become: yes
- name: start and enable mysql service
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes
- name: creating mysql user
  mysql_user:
    name: "{{ lookup('cypher','secret=secret/db_user') }}"
    password: "{{ lookup('cypher','secret=secret/db_password') }}"
    priv: '*.*:ALL'
    host: '%'
    state: present
- name: creating mysql db
  mysql_db:
    name: demo
    state: present
- name: Enable remote login to mysql
  lineinfile:
     path: /etc/mysql/mysql.conf.d/mysqld.cnf
     regexp: '^bind-address'
     line: 'bind-address = 0.0.0.0'
     backup: yes
- name: Restart mysql
  service:
    name: mysql
    state: restarted
  become: yes
