---

- name: Install the nodejs
  apt:
    name: nodejs
    state: present

- name: Install npm
  apt:
    name: npm
    state: present

- name: Install n pm2 packages
  command: npm install -g n pm2

- name: Install specific version of npm
  command: n install 14

- name: Copy chatbot code to frontend server
  copy:
    src: ./chatbot_nodejs/
    dest: /var/www/chatbot
    mode: 0755

- name: Install dependencies and start the Node.js application
  command: npm install
  args:
    chdir: /var/www/chatbot

- name: Stop the app if already running
  command: pm2 stop index.js
  args:
    chdir: /var/www/chatbot
  ignore_errors: true

- name: Start the Node.js application
  command: pm2 start index.js
  environment:
    MONGODB_URL: "{{ mongodb_connection_string }}"
  args:
    chdir: /var/www/chatbot

#- name: Start the Node.js application
#  command: node index
#  environment:
#    MONGODB_URL: "{{ mongodb_connection_string }}"
#  args:
#    chdir: /var/www/chatbot
#  async: 1000
#  poll: 0
