---

- name: Print out env var
  debug:
    var: ansible_env
    
- name: Install the nodejs
  apt:
    name: nodejs
    state: present

- name: Install npm
  apt:
    name: npm
    state: present

- name: Install n
  command: npm install -g n

- name: Install specific version of npm
  command: n install 14

- name: Install pm2 package
  command: npm install -g pm2

- name: Copy chatbot code to frontend server
  copy:
    src: ./chatbot_nodejs/
    dest: /var/www/chatbot
    mode: 0755

- name: Install dependencies and start the Node.js application
  command: npm install
  args:
    chdir: /var/www/chatbot

- name: Stop and delete the app if already running
  command: pm2 delete index.js
  args:
    chdir: /var/www/chatbot
  ignore_errors: true

- name: Start the Node.js application
  command: MONGODB_URL="{{ mongodb_connection_string }}" pm2 start index.js
  args:
    chdir: /var/www/chatbot

#- name: Start the Node.js application
#  command: node index
#  environment:
#    MONGODB_URL: "{{ mongodb_connection_string }}"
#  args:
#    chdir: /var/www/chatbot
#  async: 1000
#  poll: 0
