---

- name: Print out ansibe_env var
  debug:
    var: ansible_env

- name: Print out local env var
  debug:
    msg: "'{{ lookup('ansible.builtin.env', 'UBUNTU_IP') }}' is the UBUNTU_IP environment variable."
  
- name: Install the nodejs
  become: yes
  apt:
    name: nodejs
    state: present

- name: Install npm
  become: yes
  apt:
    name: npm
    state: present

- name: Install npm
  become: yes
  command: npm install -g n

- name: Install specific version of npm
  become: yes
  command: n install 14

- name: Install pm2 package
  become: yes
  command: npm install -g pm2

- name: Copy chatbot code to frontend server
  become: yes
  copy:
    src: ./chatbot_nodejs/
    dest: /var/www/chatbot
    mode: 0755

- name: Install dependencies and start the Node.js application
  become: yes
  command: npm install
  args:
    chdir: /var/www/chatbot

- name: Stop and delete the app if already running
  become: yes
  command: pm2 delete index.js
  args:
    chdir: /var/www/chatbot
  ignore_errors: true

#- name: Start the Node.js application
#  command: cd /var/www/chatbot/ ; MONGODB_URL="{{ mongodb_connection_string }}"  /usr/local/bin/pm2 start ./index.js
#  args:
#    chdir: /var/www/chatbot
    
- name: Start the Node.js application using shell 
  ansible.builtin.shell: |
    export MONGODB_URL="{{ mongodb_connection_string }}"
    cd /var/www/chatbot
    /usr/local/bin/pm2 start ./index.js
    exit 0
  args:
    executable: /bin/bash
    
#- name: Start the Node.js application
#  command: node index
#  environment:
#    MONGODB_URL: "{{ mongodb_connection_string }}"
#  args:
#    chdir: /var/www/chatbot
#  async: 1000
#  poll: 0
